version: '3.8'

services:
  nginx-manager:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "3001:3000"  # For direct access to management interface
    volumes:
      - proxy_cert:/etc/letsencrypt
      - certbot_webroot:/var/www/certbot
      - ./data:/app/data
      - ./nginx-config:/app/nginx-config
    networks:
      - proxy
    environment:
      - NODE_ENV=production
    # deploy:
    #   replicas: 1
    #   placement:
    #     constraints:
    #       - node.role == manager
      # restart_policy:
      #   condition: on-failure

networks:
  proxy:
    driver: bridge

volumes:
  proxy_cert:
  certbot_webroot: 